version: "3.8"
services:
  rasa_server:
    container_name: "rasa_server"
    user: root
    build: 
      context:  ./chatbot
    volumes:
    - "./chatbot:/app"
    ports: 
      - "5005:5005"
  action_server:
    container_name: "action_server"
    build: 
      context: ./chatbot/actions
    volumes:
      - ./chatbot/actions:/app/actions
      - ./chatbot/data:/app/data
    ports:
      - 5055:5055

  db:
    container_name: "postgresql_db"
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    container_name: app
    build: .
    command: bash -c "uvicorn run:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: always


volumes:
  postgres_data:

# docker-compose up -d --build
# docker-compose up -d app